import { createFileRoute } from "@tanstack/react-router";
import { StudioPageHeader, StudioPageState } from "../studio/StudioPageState";
import { useStudioState } from "../studio/queries";

export function ExtensionsPage() {
  const query = useStudioState();
  const providers = query.data?.snapshot.providers ?? [];
  const infrastructure = query.data?.extensions.filter((extension) => !providers.some((provider) => extension.package.replace(/^openbb[-_]/, "") === provider.id)) ?? [];
  return <StudioPageState error={query.error} isPending={query.isPending}><div className="mx-auto w-full max-w-6xl overflow-auto py-6"><StudioPageHeader title="扩展与数据源" description={`当前使用 ${query.data?.runtime ?? "OpenBB"} 运行环境。普通用户只需关心可用的数据源。`} action={<a className="rounded bg-theme-accent px-4 py-2 text-sm text-theme-primary-inverse" href="/advanced?section=extensions">打开底层扩展管理</a>} /><section className="mt-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">已发现的数据源</h2><p className="mt-1 text-sm text-theme-muted">配置凭证后即可在查询页面使用；无需理解 Python 包。</p></div><a className="text-sm text-theme-accent" href="/data-sources">配置数据源 →</a></div><div className="mt-3 grid grid-cols-3 gap-3">{providers.map((provider) => <a className="rounded border border-theme-outline bg-theme-primary p-4 hover:bg-theme-secondary" href={`/data-sources/${provider.id}`} key={provider.id}><div className="flex items-center justify-between"><strong>{provider.display_name}</strong><span className="text-xs text-theme-muted">{provider.version ?? "版本未知"}</span></div><p className="mt-2 text-sm text-theme-muted">提供 {provider.capability_count} 个数据集</p><span className="mt-3 block text-sm text-theme-accent">配置与测试 →</span></a>)}</div></section><details className="mt-6 rounded border border-theme-outline bg-theme-primary"><summary className="cursor-pointer p-4 font-semibold">查看 {infrastructure.length} 个底层组件</summary><div className="grid grid-cols-[1fr_8rem_8rem] gap-3 border-t border-theme-outline p-3 text-xs text-theme-muted"><span>包名</span><span>版本</span><span>安装方式</span></div>{infrastructure.map((extension) => <div className="grid grid-cols-[1fr_8rem_8rem] gap-3 border-t border-theme-outline p-3 text-sm" key={`${extension.package}:${extension.version}`}><strong>{extension.package}</strong><span>{extension.version}</span><span>{extension.install_method}</span></div>)}</details><section className="mt-6 rounded border border-theme-outline bg-theme-primary p-5"><h2 className="font-semibold">安装流程</h2><ol className="mt-3 grid grid-cols-5 gap-3 text-sm">{["1. 安装", "2. 发现数据源", "3. 应用配置", "4. 重启服务", "5. 验证可用"].map((stage) => <li className="rounded bg-theme-secondary p-3" key={stage}>{stage}</li>)}</ol><p className="mt-3 text-sm text-theme-muted">整个流程继续使用 OpenBB Desktop 原有的受控安装器，不要求用户输入包管理命令。</p></section></div></StudioPageState>;
}
export const Route = createFileRoute("/extensions")({ component: ExtensionsPage });
